### ISSUE TITLE
Add header

### ISSUE THREAD

**Issue by pavi2410** [pavi2410/URL-Inspector#5]

**Comment by g0lc0de** [comment]
Can you explain how the header should look like?

**Comment by pavi2410** [comment]
As simple and minimal as this.
![_191027_222014_014](https://user-images.githubusercontent.com/28837746/67638215-15a99280-f908-11e9-9f85-c8631e43d779.jpg)

**Comment by pavi2410** [comment]
This will be the icon -> 🕵️

**Comment by pavi2410** [comment]
The font is monospace

**Comment by pavi2410** [comment]
Example: https://jgthms.com/

**Comment by g0lc0de** [comment]
Okay, I will start working on it
