### ISSUE TITLE
Use monospace font

### ISSUE THREAD

**Issue by pavi2410** [pavi2410/URL-Inspector#7]

**Comment by smolindamix** [comment]
Have you a preference for the font of monospace category ?

**Comment by pavi2410** [comment]
No preference but as this project is pure Vanilla and zero dependencies. So I would use system default monospace font.

**Comment by faahim** [comment]
Looks like this isn't taken on yet? Can I do this?

One question on the issue: Do we want to use Monospace font for the whole page for some parts (maybe just the table? :thinking: ) only?

Let me know! :slightly_smiling_face:

**Comment by faahim** [comment]
Ugh, couldn't resist just doing it! :sweat_smile: 

PR #13 should address this issue. More details there. :slightly_smiling_face:

**Comment by pavi2410** [comment]
All of the page

**Comment by faahim** [comment]
Great! I did implement it to be applied to the whole page! :)

**Comment by pavi2410** [comment]
Closed by #13
